name: newsly_app
description: newsly is an app to delivered to you the new news .
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.0
  cloud_firestore: ^3.1.7
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2
  flutter_staggered_animations: ^1.0.0
  flutter_vector_icons: ^1.0.0
  formz: ^0.4.1
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
 
  json_annotation: ^4.4.0
  logger: ^1.1.0
  rxdart: ^0.27.3
  share_plus: ^3.0.4
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  timeago: ^3.1.0
  webview_flutter: ^3.0.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  animations: ^2.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.7
  device_preview: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  flutter_native_splash: ^2.0.2
flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_icon/newsLogo.png
  color_dark: "#1c1c1c"
  image_dark: assets/logo_icon/newsLogo_light.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo_icon/
